datasources.default.url=jdbc:sqlite:file:identity-it?mode=memory&cache=shared&foreign_keys=on
datasources.default.driver-class-name=org.sqlite.JDBC
datasources.default.db-type=sqlite
micronaut.security.token.jwt.signatures.secret.generator.secret=integration-test-secret-integration-test-secret
